// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: proto/stats/v1/stats.proto

package statsv1

import (
	v1 "github.com/studio/platform/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	NewUsersToday int64                  `protobuf:"varint,2,opt,name=new_users_today,json=newUsersToday,proto3" json:"new_users_today,omitempty"`
	TotalPosts    int64                  `protobuf:"varint,3,opt,name=total_posts,json=totalPosts,proto3" json:"total_posts,omitempty"`
	TotalReports  int64                  `protobuf:"varint,4,opt,name=total_reports,json=totalReports,proto3" json:"total_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardStats) Reset() {
	*x = DashboardStats{}
	mi := &file_proto_stats_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardStats) ProtoMessage() {}

func (x *DashboardStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardStats.ProtoReflect.Descriptor instead.
func (*DashboardStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardStats) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *DashboardStats) GetNewUsersToday() int64 {
	if x != nil {
		return x.NewUsersToday
	}
	return 0
}

func (x *DashboardStats) GetTotalPosts() int64 {
	if x != nil {
		return x.TotalPosts
	}
	return 0
}

func (x *DashboardStats) GetTotalReports() int64 {
	if x != nil {
		return x.TotalReports
	}
	return 0
}

type ChartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartRequest) Reset() {
	*x = ChartRequest{}
	mi := &file_proto_stats_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartRequest) ProtoMessage() {}

func (x *ChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartRequest.ProtoReflect.Descriptor instead.
func (*ChartRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *ChartRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ChartPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartPoint) Reset() {
	*x = ChartPoint{}
	mi := &file_proto_stats_v1_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartPoint) ProtoMessage() {}

func (x *ChartPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_v1_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartPoint.ProtoReflect.Descriptor instead.
func (*ChartPoint) Descriptor() ([]byte, []int) {
	return file_proto_stats_v1_stats_proto_rawDescGZIP(), []int{2}
}

func (x *ChartPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ChartPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_proto_stats_v1_stats_proto protoreflect.FileDescriptor

const file_proto_stats_v1_stats_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/stats/v1/stats.proto\x12\bstats.v1\x1a\x1cproto/common/v1/common.proto\"\x9f\x01\n" +
	"\x0eDashboardStats\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12&\n" +
	"\x0fnew_users_today\x18\x02 \x01(\x03R\rnewUsersToday\x12\x1f\n" +
	"\vtotal_posts\x18\x03 \x01(\x03R\n" +
	"totalPosts\x12#\n" +
	"\rtotal_reports\x18\x04 \x01(\x03R\ftotalReports\"\"\n" +
	"\fChartRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"6\n" +
	"\n" +
	"ChartPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value2\x93\x01\n" +
	"\fStatsService\x12?\n" +
	"\x11GetDashboardStats\x12\x10.common.v1.Empty\x1a\x18.stats.v1.DashboardStats\x12B\n" +
	"\x10StreamUserGrowth\x12\x16.stats.v1.ChartRequest\x1a\x14.stats.v1.ChartPoint0\x01B3Z1github.com/studio/platform/proto/stats/v1;statsv1b\x06proto3"

var (
	file_proto_stats_v1_stats_proto_rawDescOnce sync.Once
	file_proto_stats_v1_stats_proto_rawDescData []byte
)

func file_proto_stats_v1_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_v1_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_v1_stats_proto_rawDesc), len(file_proto_stats_v1_stats_proto_rawDesc)))
	})
	return file_proto_stats_v1_stats_proto_rawDescData
}

var file_proto_stats_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_stats_v1_stats_proto_goTypes = []any{
	(*DashboardStats)(nil), // 0: stats.v1.DashboardStats
	(*ChartRequest)(nil),   // 1: stats.v1.ChartRequest
	(*ChartPoint)(nil),     // 2: stats.v1.ChartPoint
	(*v1.Empty)(nil),       // 3: common.v1.Empty
}
var file_proto_stats_v1_stats_proto_depIdxs = []int32{
	3, // 0: stats.v1.StatsService.GetDashboardStats:input_type -> common.v1.Empty
	1, // 1: stats.v1.StatsService.StreamUserGrowth:input_type -> stats.v1.ChartRequest
	0, // 2: stats.v1.StatsService.GetDashboardStats:output_type -> stats.v1.DashboardStats
	2, // 3: stats.v1.StatsService.StreamUserGrowth:output_type -> stats.v1.ChartPoint
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stats_v1_stats_proto_init() }
func file_proto_stats_v1_stats_proto_init() {
	if File_proto_stats_v1_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_v1_stats_proto_rawDesc), len(file_proto_stats_v1_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_v1_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_v1_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_v1_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_v1_stats_proto = out.File
	file_proto_stats_v1_stats_proto_goTypes = nil
	file_proto_stats_v1_stats_proto_depIdxs = nil
}
