// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.2
// source: proto/stats/v1/stats.proto

package statsv1

import (
	context "context"
	v1 "github.com/studio/platform/proto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_GetDashboardStats_FullMethodName = "/stats.v1.StatsService/GetDashboardStats"
	StatsService_StreamUserGrowth_FullMethodName  = "/stats.v1.StatsService/StreamUserGrowth"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetDashboardStats(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*DashboardStats, error)
	StreamUserGrowth(ctx context.Context, in *ChartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChartPoint], error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetDashboardStats(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*DashboardStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardStats)
	err := c.cc.Invoke(ctx, StatsService_GetDashboardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) StreamUserGrowth(ctx context.Context, in *ChartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChartPoint], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StatsService_ServiceDesc.Streams[0], StatsService_StreamUserGrowth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChartRequest, ChartPoint]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StatsService_StreamUserGrowthClient = grpc.ServerStreamingClient[ChartPoint]

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	GetDashboardStats(context.Context, *v1.Empty) (*DashboardStats, error)
	StreamUserGrowth(*ChartRequest, grpc.ServerStreamingServer[ChartPoint]) error
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) GetDashboardStats(context.Context, *v1.Empty) (*DashboardStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedStatsServiceServer) StreamUserGrowth(*ChartRequest, grpc.ServerStreamingServer[ChartPoint]) error {
	return status.Error(codes.Unimplemented, "method StreamUserGrowth not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call panics, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetDashboardStats(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_StreamUserGrowth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatsServiceServer).StreamUserGrowth(m, &grpc.GenericServerStream[ChartRequest, ChartPoint]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StatsService_StreamUserGrowthServer = grpc.ServerStreamingServer[ChartPoint]

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.v1.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardStats",
			Handler:    _StatsService_GetDashboardStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUserGrowth",
			Handler:       _StatsService_StreamUserGrowth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/stats/v1/stats.proto",
}
