// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: proto/moderation/v1/moderation.proto

package moderationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewTextRequest) Reset() {
	*x = ReviewTextRequest{}
	mi := &file_proto_moderation_v1_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewTextRequest) ProtoMessage() {}

func (x *ReviewTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moderation_v1_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewTextRequest.ProtoReflect.Descriptor instead.
func (*ReviewTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_moderation_v1_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReviewImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewImageRequest) Reset() {
	*x = ReviewImageRequest{}
	mi := &file_proto_moderation_v1_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewImageRequest) ProtoMessage() {}

func (x *ReviewImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moderation_v1_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewImageRequest.ProtoReflect.Descriptor instead.
func (*ReviewImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_moderation_v1_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewImageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ReviewResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResult) Reset() {
	*x = ReviewResult{}
	mi := &file_proto_moderation_v1_moderation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResult) ProtoMessage() {}

func (x *ReviewResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moderation_v1_moderation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResult.ProtoReflect.Descriptor instead.
func (*ReviewResult) Descriptor() ([]byte, []int) {
	return file_proto_moderation_v1_moderation_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewResult) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ReviewResult) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_proto_moderation_v1_moderation_proto protoreflect.FileDescriptor

const file_proto_moderation_v1_moderation_proto_rawDesc = "" +
	"\n" +
	"$proto/moderation/v1/moderation.proto\x12\rmoderation.v1\"'\n" +
	"\x11ReviewTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"&\n" +
	"\x12ReviewImageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"B\n" +
	"\fReviewResult\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels2\xaf\x01\n" +
	"\x11ModerationService\x12K\n" +
	"\n" +
	"ReviewText\x12 .moderation.v1.ReviewTextRequest\x1a\x1b.moderation.v1.ReviewResult\x12M\n" +
	"\vReviewImage\x12!.moderation.v1.ReviewImageRequest\x1a\x1b.moderation.v1.ReviewResultB=Z;github.com/studio/platform/proto/moderation/v1;moderationv1b\x06proto3"

var (
	file_proto_moderation_v1_moderation_proto_rawDescOnce sync.Once
	file_proto_moderation_v1_moderation_proto_rawDescData []byte
)

func file_proto_moderation_v1_moderation_proto_rawDescGZIP() []byte {
	file_proto_moderation_v1_moderation_proto_rawDescOnce.Do(func() {
		file_proto_moderation_v1_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_moderation_v1_moderation_proto_rawDesc), len(file_proto_moderation_v1_moderation_proto_rawDesc)))
	})
	return file_proto_moderation_v1_moderation_proto_rawDescData
}

var file_proto_moderation_v1_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_moderation_v1_moderation_proto_goTypes = []any{
	(*ReviewTextRequest)(nil),  // 0: moderation.v1.ReviewTextRequest
	(*ReviewImageRequest)(nil), // 1: moderation.v1.ReviewImageRequest
	(*ReviewResult)(nil),       // 2: moderation.v1.ReviewResult
}
var file_proto_moderation_v1_moderation_proto_depIdxs = []int32{
	0, // 0: moderation.v1.ModerationService.ReviewText:input_type -> moderation.v1.ReviewTextRequest
	1, // 1: moderation.v1.ModerationService.ReviewImage:input_type -> moderation.v1.ReviewImageRequest
	2, // 2: moderation.v1.ModerationService.ReviewText:output_type -> moderation.v1.ReviewResult
	2, // 3: moderation.v1.ModerationService.ReviewImage:output_type -> moderation.v1.ReviewResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_moderation_v1_moderation_proto_init() }
func file_proto_moderation_v1_moderation_proto_init() {
	if File_proto_moderation_v1_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_moderation_v1_moderation_proto_rawDesc), len(file_proto_moderation_v1_moderation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_moderation_v1_moderation_proto_goTypes,
		DependencyIndexes: file_proto_moderation_v1_moderation_proto_depIdxs,
		MessageInfos:      file_proto_moderation_v1_moderation_proto_msgTypes,
	}.Build()
	File_proto_moderation_v1_moderation_proto = out.File
	file_proto_moderation_v1_moderation_proto_goTypes = nil
	file_proto_moderation_v1_moderation_proto_depIdxs = nil
}
