apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: studio-dev

bases:
- ../../base

nameSuffix: -dev

replicas:
- name: studio-backend
  count: 1
- name: studio-frontend
  count: 1

patches:
- target:
    kind: Deployment
    name: studio-backend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/studio/backend:dev
- target:
    kind: Deployment
    name: studio-frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/studio/frontend:dev
